- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Ensure python is available
      raw: test -e /usr/bin/python || apt install -y --allow-unauthenticated python-minimal

    - name: Ensure python-apt is available
      raw: test -d /usr/share/python-apt || apt install -y --allow-unauthenticated python-apt

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade

- hosts: bb
  remote_user: root
  tasks:
      - name: Install git
        apt:
            name: git-core
            update_cache: yes

      - name: Get bitbucket installer
        get_url:
            url: https://ipfs.subutai.io/ipfs/QmcpYaprFHkT5jdKKco3kqjA3ZxvcXnViAiT1ynWMhyz1X/atlassian-bitbucket-5.11.4-x64.bin
            dest: /tmp/bitbucket.bin
            mode: 0774


      - name: Copy varfile 
        copy:
            dest: "/tmp/varfile.cfg"
            content: |
                launch.application$Boolean=true
                sys.adminRights$Boolean=true
                app.install.service$Boolean=true
                app.defaultInstallDir=/opt/atlassian/bitbucket/5.11.1
                serverPort=8006
                sys.languageId=en
                httpPort=7990
                app.bitbucketHome=/var/atlassian/application-data/bitbucket
                executeLauncherAction$Boolean=true


      - name: Run installer
        shell: |
             /tmp/bitbucket.bin -q -varfile /tmp/varfile.cfg
